### ISSUE TITLE
What else is missing?

### ISSUE THREAD

**Issue by willirath** [ESM-VFC/esm-vfc-stacks#10]
- @koldunovn and @suvarchal Should we add `pyfesom` and `pangaeapy` directly to this image?

- And do we need any more `pyviz` related things?

- What about `pytest`?

**Comment by koldunovn** [comment]
I still have to make `pyfesom2` installable at least through pip. Or installation from the repository will also work?

**Comment by suvarchal** [comment]
@koldunovn master should be installable via pip in environment.yml

 - pip:
    - git+https://github.com/FESOM/pyfesom2#egg=pyfesom2

**Comment by suvarchal** [comment]
i like pipenv way of separating requirements vs development requirements like pytest, wish conda had that(?).

**Comment by willirath** [comment]
@suvarchal For now, I'd rather include all the dev requirements in the env, because the separation between user and developer is not really present. Later, an easy separation would be great. But I don't see a conda-native way of indicating "this env for dev" and "this env for users". Simplest way I see is having an additional `environment-esm-vfc-dev.yml` file.

@koldunovn: I'll add a PR that tries installing `pyfesom2` from your current `master`.

**Comment by koldunovn** [comment]
I hope to manage to do pip/conda installation soon.

**Comment by willirath** [comment]
What keeps you from doing this? Time / effort or technical issues?

**Comment by koldunovn** [comment]
Ok, @willirath , you made me feel bad about it, and I create the package at PyPI :) You can try your luck with 
```bash
pip install pyfesom2
```

Still working on the conda version.

**Comment by willirath** [comment]
That was not my intention. Sorry if that poor any pressure on you.

**Comment by koldunovn** [comment]
It should have been done half a year ago :) You gave me a nice reason :)
