### ISSUE TITLE
Not able to run with --ip="127.0.0.1"

### ISSUE THREAD

**Issue by koldunovn** [ESM-VFC/esm-vfc-stacks#24]
Tryin to run Docker container on mac. The `--ip="127.0.0.1"` did not work, there was nothin working on the specified port. However the: `--ip="0.0.0.0"` worked as expected.

@willirath

**Comment by willirath** [comment]
Ah, yes, this seems to be wrong.

**Comment by koldunovn** [comment]
Just additional small thing - might be worth to replace `<Tag>` by just `latest`.

**Comment by willirath** [comment]
Not sure. It seems `docker run` does not look for a changed `latest` if it already finds a local image. We'd have to add an explicit `docker pull` to ensure `latest` really is the latest from Dockerhub.

**Comment by koldunovn** [comment]
Just can be confusing for the fresh user :) Maybe just add that is you want to update the image do docker pull?

**Comment by willirath** [comment]
I'd change to

> ```shell
> docker pull esmvfc/esm-vfc-stacks:latest
> docker run \
>     -v ${HOME}/work/:/work -w /work \
>     -p 8888:8888 esmvfc/esm-vfc-stacks:latest \
>     jupyter lab --no-browser --ip="127.0.0.1" --port="8888"
> ```
> If you want to run a specific version of this image, replace the `latest` accordingly. All available versions [are found on Dockerhub](https://hub.docker.com/r/esmvfc/esm-vfc-stacks/tags).

**Comment by willirath** [comment]
> Just can be confusing for the fresh user :)

Like the user who opened #21? :)

**Comment by koldunovn** [comment]
> > Just can be confusing for the fresh user :)
> 
> Like the user who opened #21? :)

Yes, this guy :)

**Comment by willirath** [comment]
Reopening so I don't forget to actually update the README.
